provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  # load a static html from the provided url
  loadhtml:
    lang: forward-go
    handler: ./loadhtml
    image: s8sg/loadhtml:latest
    environment:
        # Default input type for forward function is multipart file
        input_type: "POST"
        async: false
        forward: matchregex
        content_type: "text/html"

  # match Regex on a given string and produce a output as json
  matchregex:
    lang: forward-go
    handler: ./matchregex
    image: s8sg/matchregex:latest
    environment:
        regex: "(http|ftp|https)://([\\w_-]+(?:(?:\\.[\\w_-]+)+))([\\w.,@?^=%&:/~+#-]*[\\w@?^=%&/~+#-])?"
        forward: jsonpage
        async: false
        content_type: "application/json"
  
  # Make a html page from json 
  jsonpage:
    lang: forward-go
    handler: ./jsonpage
    image: s8sg/jsonpage:latest
    environment:
        async: false
        #forward: htmlhost
        content_type: "text/html"

  # html host
  #htmlhost:
  #  lang: dockerfile
  #  handler: ./htmlhost
  #  image: s8sg/htmlhost:latest
